services:
  postgres:
    image: postgres:18.1
    container_name: postgres_pim
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      -   pim_scraper_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  etl_pim:
    build: .
    container_name: scraper_pim
    command: ["python", "etl_pim.py"] 
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pim_scraper_net

volumes:
  pgdata:

networks:
  pim_scraper_net:
    driver: bridge
